services:
  - type: web
    name: expense-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: expense_tracker_db
          property: connectionString
      - key: RENDER
        value: "true"

databases:
  - name: expense_tracker_db
    databaseName: expense_tracker
    user: expense_tracker_user 